language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: false
cache:
  directories:
    - "$HOME/.m2"
install: true
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
    - jdk: openjdk13
    - jdk: openjdk15
    - jdk: openjdk-ea
  allow_failures:
    #seems lombok-maven-plugin does not support JDK14 right now.
    - jdk: openjdk15
    - jdk: openjdk-ea
script:
  - "./mvnw clean install -U -Dmaven.javadoc.skip=false"
