language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: false
cache:
  directories:
    - "$HOME/.m2"
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: linux
      jdk: openjdk13
    - os: linux
      jdk: openjdk14
script:
  - "./mvnw clean install site -U -Dmaven.javadoc.skip=false"
  - "if [ test \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then; ./mvnw sonar:sonar -Dsonar.projectKey=cyanpotion_cyan_potion -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=133240d1ee4abeaa8b7ba1ef36cab1a2b789ddcb ; fi"
  - "cd ./src/"
  - "cd ./base/"
  - "../../mvnw clean install site -U -Dmaven.javadoc.skip=false"
  - "if [ test \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then; ../../mvnw sonar:sonar -Dsonar.projectKey=cyan_potion_base -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=553972c4c1b0147c484f07f8741d76b24d51415c ; fi"
  - "cd ../"
  - "cd ./coordinate"
  - "../../mvnw clean install site -U -Dmaven.javadoc.skip=false"
  - "if [ test \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then; ../../mvnw sonar:sonar -Dsonar.projectKey=cyan_potion_coordinate -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3b4953bb762221ad019f1a4d2cfd37b0830e326f ; fi"
  - "cd ../"
  - "cd ./rpg_module"
  - "../../mvnw clean install site -U -Dmaven.javadoc.skip=false"
  - "if [ test \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then; ../../mvnw sonar:sonar -Dsonar.projectKey=cyan_potion_rpg_module -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e50335ce1fed53dfa9ad4ce70995957336cf8e7e ; fi"
  - "cd ../"
  - "cd ./demo"
  - "../../mvnw clean install site -U -Dmaven.javadoc.skip=false"