language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
matrix:
  include:
    - os: linux x64
      jdk: openjdk12
    - os: linux x64
      jdk: openjdk-ea
script:
  - ./mvnw clean package -Dmaven.javadoc.skip=false