[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# 根源
> mmd.emoticon=`tree`


## 引擎

### z轴

## 游戏

### 地图，节点图。map

#### 势力，经济系统

##### 战争

## 旁侧

### icon小图片渲染
